kind: Cluster

apiVersion: kind.x-k8s.io/v1alpha4

nodes:

# Master node
- role: control-plane
  extraMounts:
  - hostPath: /Users/ysharma/Documents/Kubernetes/storage  # This is the mac laptop path where we want to store jenkins data
    containerPath: /mnt/data
  - hostPath: /var/run/docker.sock  # This is needed to run docker as a slave node inside a jenkins server inside a container
    containerPath: /var/run/docker.sock

  extraPortMappings:
  # Mapping jenkins nodeport 31000 to machines localhost:31000
  - containerPort: 31000
    hostPort: 31000
    listenAddress: "0.0.0.0"   # Note: binding the listenAddress to 127.0.0.1 may affect your ability to access the service
    protocol: TCP

  - containerPort: 80
    hostPort: 80
    protocol: TCP

  - containerPort: 443
    hostPort: 443
    protocol: TCP

  # Ingress controller setup for Kind specific
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"


